version:0.0
os: linux
files:
  - sources
   destination: /var/www/html
hooks:
  AfterInstall:
   - location: scripts/install_nginx.sh
     time: 300
     runs: root
  ApplicationStart:
  -location: scripts/start_nginx.sh
     timeout: 300
     runs: root